--[[==========================================================================
	KINGS PRODUCTION · LICENSE SYSTEM  (v2.1)
	Version: 2.1

	WHAT THIS IS
	------------
	This script locks your Roblox system (e.g. your Music System) to the
	Kings Production licensing portal. When the game runs, this script asks
	the portal "is this system licensed?" and only lets your system run if
	the answer is YES.

	HOW TO INSTALL (3 steps)
	------------------------
	1. Fill in your SYSTEM NAME and SYSTEM PASSWORD below — the same ones you
	   registered on kingsproduction.cc (Dashboard → Register System).
	2. Put this script into ServerScriptService (or inside your system's
	   main folder).
	3. Roblox Studio → Game Settings → Security → enable "Allow HTTP Requests".

	⚠ IMPORTANT: the fully locked copy is generated by the site — Dashboard →
	   your system → "Studio code". That copy has the anti-tamper fingerprint
	   filled in. Use it for anything you ship. This file is the working spec:
	   TAMPER_KEY stays "" here, which disables the fingerprint check so you
	   can iterate without breaking it.

HOW IT WORKS
------------
- On game start: sends System Name + Password to the portal → ACTIVE or DENIED.
- NEW GAMES START UNAPPROVED: the first check registers the game on the
  web and the system creator must ALLOW it from the Licensed Dashboard
  (Registered Systems → Games) before it runs.
- Every few minutes: a "heartbeat" re-checks, so if you PAUSE the license
  or KICK a device on the web, the game reacts within minutes.
	- Kicked devices are DENIED on their next check-in, and any kicked player
	  is force-disconnected (auto-kick) even mid-game.
	- If DENIED: the protected object is disabled and License.OnDenied fires.

	ANTI-TAMPER
	-----------
	The shipped copy embeds a SHA-256 fingerprint of its own source. Roblox
	hides script.Source from live servers, so the fingerprint check runs in
	Studio (where it is enforced hard) and is skipped automatically in a
	published game — there the protection is the portal itself: pause / kick /
	device denial, plus obfuscation. Obfuscate before shipping; the password
	lives inside the script and obfuscation makes pulling it out much harder.

API CONTRACT (what the portal returns)
--------------------------------------
POST https://kingsproduction.cc/api/systems/activate
POST https://kingsproduction.cc/api/systems/heartbeat
Body:  { systemName, systemPassword, deviceId, deviceName, placeId,
         gameName, gameOwner, gameOwnerType }
Reply: { ok: true, data: { active: true|false, reason: "...",
                           revokedPlayers: ["123","456"] } }

POST https://kingsproduction.cc/api/systems/device   (player registration)
Body:  { systemName, systemPassword, playerId, playerName, placeId,
         gameName, gameOwner, gameOwnerType }
Reply: { ok: true, data: { active: true|false, reason: "...", kicked: true|false } }
============================================================================--]]

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")

-- ⚙ CONFIGURE THESE — fill in from your kingsproduction.cc account
local CONFIG = {
	SystemName = "__SYSTEM_NAME__",          -- ← YOUR registered system name
	SystemPassword = "__SYSTEM_PASSWORD__",  -- ← YOUR registered system password

	ApiUrl = "https://kingsproduction.cc/api/systems/activate",
	HeartbeatUrl = "https://kingsproduction.cc/api/systems/heartbeat",
	PlayerUrl = "https://kingsproduction.cc/api/systems/device",

	HeartbeatSeconds = 300,                  -- re-check every 5 minutes
	RetrySeconds = 15,                       -- retry interval when a check fails
	RequestTimeout = 10,                     -- give up on a request after ~10s
	ProtectedObjectName = "__PROTECTED_OBJECT__",  -- script/object to disable when unlicensed
}

-- ANTI-TAMPER — do not remove. The site pre-computes this fingerprint from
-- this exact script. If the script is edited (license check stripped), the
-- fingerprint stops matching and the system hard-fails instead of running.
-- ("" = unlocked spec copy — the site's "Studio code" button fills it in.)
local TAMPER_KEY = "__FINGERPRINT__"

-- Roblox's crypt.hash returns a BASE64-encoded SHA-256; the site bakes the
-- same encoding. script.Source is only readable in Studio, so in a live game
-- this check is skipped automatically — the portal's pause/kick is the real
-- protection there.
local function fingerprint()
	local src = script.Source
	if src == "" then return "" end -- live server: source hidden, skip check
	src = string.gsub(src, "\r\n", "\n") -- line-ending normalization
	src = string.gsub(src, 'local TAMPER_KEY = "[^"]*"', 'local TAMPER_KEY = ""')
	return string.sub(crypt.hash(src, Enum.CryptHashAlgorithm.SHA256), 1, 12)
end
if TAMPER_KEY ~= "" and script.Source ~= "" and fingerprint() ~= TAMPER_KEY then
	error("[License] This script has been modified — the license cannot be removed without rewriting the script.")
end

local License = {}
License.IsActive = false
License.LastCheck = 0
License.LastError = nil
License.OnDenied = nil                    -- optional callback when license dies

local ProtectedObject = nil

local function log(msg)
	warn("[License] " .. tostring(msg))
end

-- Only Scripts / LocalScripts have a Disabled property — disable those safely
-- and leave everything else to the License.IsLicensed() gate.
local function setProtectedDisabled(disabled)
	if not ProtectedObject then return end
	if ProtectedObject:IsA("Script") or ProtectedObject:IsA("LocalScript") then
		ProtectedObject.Disabled = disabled
	end
end

-- POST a JSON payload with a hard timeout, return the decoded response (or nil)
local function post(url, payload)
	local body = HttpService:JSONEncode(payload)
	local ok, res = false, nil
	local done = false
	task.spawn(function()
		ok, res = pcall(function()
			return HttpService:RequestAsync({
				Url = url,
				Method = "POST",
				Headers = { ["Content-Type"] = "application/json" },
				Body = body,
			})
		end)
		done = true
	end)
	local waited = 0
	while not done and waited < CONFIG.RequestTimeout do
		task.wait(1)
		waited = waited + 1
	end
	if not done then
		License.LastError = "Request timed out"
		return nil
	end
	if not ok or not res then
		License.LastError = "Request failed"
		return nil
	end
	local okDecode, json = pcall(function()
		return HttpService:JSONDecode(res.Body)
	end)
	if not okDecode then
		License.LastError = "Bad response"
		return nil
	end
	return json
end

-- Force-kick every player whose device was kicked by the creator.
local function kickPlayers(ids)
	if type(ids) ~= "table" then return end
	for _, id in ipairs(ids) do
		local player = Players:GetPlayerByUserId(tonumber(id))
		if player then
			log("Kicking unauthorized player " .. player.Name)
			player:Kick("This device is not authorized for this system.")
		end
	end
end

local function applyDecision(res)
	local active = res and res.ok == true and res.data and res.data.active == true
	License.IsActive = active
	License.LastCheck = os.time()
	if active then
		log("ACTIVE — system is licensed")
	else
		log("DENIED — " .. tostring(res and res.data and res.data.reason or "license not active") .. " — disabling protected system")
	end
	setProtectedDisabled(not active)
	kickPlayers(res and res.data and res.data.revokedPlayers)
	if not active and License.OnDenied then
		License.OnDenied()
	end
end

-- A stable, readable label for the device list on the web dashboard.
local function deviceLabel()
	local jobId = tostring(game.JobId)
	if jobId ~= "" and jobId ~= "0" then
		return "Server " .. string.sub(jobId, 1, 8)
	end
	return "Studio"
end

-- One full check: first run uses /activate, later runs use /heartbeat
local function creatorLabel()
	-- e.g. "User 12345" or "Group 9876" — shown on the web dashboard
	return tostring(game.CreatorType) .. " " .. tostring(game.CreatorId)
end
local function check(heartbeat)
	local payload = {
		systemName = CONFIG.SystemName,
		systemPassword = CONFIG.SystemPassword,
		deviceId = tostring(game.JobId),   -- per-server id; pair with UserId for device view
		deviceName = deviceLabel(),
		placeId = tostring(game.PlaceId),  -- so the creator sees (and can gate) each game using the system
		gameName = game.Name,
		gameOwner = creatorLabel(),
		gameOwnerType = tostring(game.CreatorType),
	}
	local res = post(heartbeat and CONFIG.HeartbeatUrl or CONFIG.ApiUrl, payload)
	if res then
		applyDecision(res)
	else
		-- Network blip: do NOT kill a licensed game over one failed request.
		log("check failed (" .. tostring(License.LastError) .. "), retrying in " .. CONFIG.RetrySeconds .. "s")
	end
end

-- Register a player so the creator can see active devices on the web, and
-- kick immediately if that player's device was already kicked.
local function registerPlayer(player)
	task.spawn(function()
	local res = post(CONFIG.PlayerUrl, {
		systemName = CONFIG.SystemName,
		systemPassword = CONFIG.SystemPassword,
		playerId = tostring(player.UserId),
		playerName = player.Name,
		placeId = tostring(game.PlaceId),  -- registers which game the player is using the system in
		gameName = game.Name,
		gameOwner = creatorLabel(),
		gameOwnerType = tostring(game.CreatorType),
	})
		if res and res.ok == true and res.data and res.data.active == false and res.data.kicked then
			player:Kick("This device is not authorized for this system.")
		end
	end)
end

-- Start the license system. Pass the object to disable when unlicensed.
function License.Start(protectedObject)
	ProtectedObject = protectedObject or script
	check(false)

	task.spawn(function()
		while true do
			task.wait(CONFIG.HeartbeatSeconds)
			check(true)
		end
	end)

	Players.PlayerAdded:Connect(registerPlayer)
	for _, p in ipairs(Players:GetPlayers()) do
		registerPlayer(p)
	end
end

-- Call from your own scripts: if false, refuse to run protected features
function License.IsLicensed()
	return License.IsActive
end

return License
